### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/Srg2Source#10]
From a user in the ForgeGradle IRC channel:

Project: https://git.gildedgames.com/GildedGames/Aether-1.8
Full Stacktrace: https://gist.github.com/matthewprenger/a4b4d4c5ddc2451bd914
Relevant bits:
```
java.lang.NullPointerException
	at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:251)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1184)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:807)
	at net.minecraftforge.srg2source.util.Util.createUnit(Util.java:350)
	at net.minecraftforge.srg2source.ast.RangeExtractor.generateRangeMap(RangeExtractor.java:138)
	at net.minecraftforge.srg2source.ast.RangeExtractor.generateRangeMap(RangeExtractor.java:88)
	at net.minecraftforge.gradle.tasks.ExtractS2SRangeTask.generateRangeMap(ExtractS2SRangeTask.java:100)
```

**Comment by Collin1971** [comment]
The issue wasn't reproducible before commit [271fad13](https://git.gildedgames.com/GildedGames/Aether-1.8/commit/271fad13875506eb4ceb0506e7c2053178a3f7d9), but after reviewing the code introduced by it I still can't see why remapping would consistently fail.

**Comment by LexManos** [comment]
Please go through and see what you can do about making a smaller test case then 'this entire mod!'

**Comment by LexManos** [comment]
Closing as this is most likely been fixed int he rework to use the latest eclipse JDT to support J8 and lambdas. If this is still a issue. Privide more details such as the partial code that's actually erroring.
This can be done by getting the range map file and whatever class is being parsed last is the culperate.
