### ISSUE TITLE
Remapping failes because of missing localisation.

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/Srg2Source#31]
I am running a win 10 (1903) and the system lang is german. I tried to update the mapping of a 1.12 project (to 1.13 mappings). But it did not change any file so I checked the logs (by running it froim cmd)

Version: 0.1 (fatjar)

Error:
```
Missing resource : org/eclipse/jdt/internal/compiler/batch/messages.properties for locale de_DE
java.util.MissingResourceException: Can't find bundle for base name org.eclipse.jdt.internal.compiler.batch.messages, locale de_DE
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at org.eclipse.jdt.internal.compiler.batch.Main$ResourceBundleFactory.getBundle(Main.java:1294)
        at org.eclipse.jdt.internal.compiler.batch.Main.relocalize(Main.java:4556)
        at org.eclipse.jdt.internal.compiler.batch.Main.relocalize(Main.java:4550)
        at org.eclipse.jdt.internal.compiler.batch.Main.<init>(Main.java:1499)
        at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:238)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1193)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:812)
        at net.minecraftforge.srg2source.util.Util.createUnit(Util.java:361)
        at net.minecraftforge.srg2source.ast.RangeExtractor.generateRangeMap(RangeExtractor.java:165)
        at net.minecraftforge.remapper.RemapperTask.extractRange(RemapperTask.java:128)
        at net.minecraftforge.remapper.RemapperTask.runRemapMod_Thread(RemapperTask.java:46)
        at net.minecraftforge.remapper.RemapperTask$1.run(RemapperTask.java:39)
        at java.lang.Thread.run(Unknown Source)
```

Also log is full of these:
```
Warning: NLS missing message: WM_errors in: org.eclipse.core.internal.utils.messages
Warning: NLS missing message: WM_jobName in: org.eclipse.core.internal.utils.messages
Warning: NLS missing message: WM_nativeErr in: org.eclipse.core.internal.utils.messages
```

**Comment by mcenderdragon** [comment]
Setting locale to "en_US" also did not work.
Cmd:
`java -D"user.language=en" -D"user.country=US" -jar .\remapper-0.1-fatjar.jar`
Output:
```
Missing resource : org/eclipse/jdt/internal/compiler/batch/messages.properties for locale en_US
java.util.MissingResourceException: Can't find bundle for base name org.eclipse.jdt.internal.compiler.batch.messages, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at org.eclipse.jdt.internal.compiler.batch.Main$ResourceBundleFactory.getBundle(Main.java:1294)
        at org.eclipse.jdt.internal.compiler.batch.Main.relocalize(Main.java:4556)
        at org.eclipse.jdt.internal.compiler.batch.Main.relocalize(Main.java:4550)
        at org.eclipse.jdt.internal.compiler.batch.Main.<init>(Main.java:1499)
        at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:238)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1193)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:812)
        at net.minecraftforge.srg2source.util.Util.createUnit(Util.java:361)
        at net.minecraftforge.srg2source.ast.RangeExtractor.generateRangeMap(RangeExtractor.java:165)
        at net.minecraftforge.remapper.RemapperTask.extractRange(RemapperTask.java:128)
        at net.minecraftforge.remapper.RemapperTask.runRemapMod_Thread(RemapperTask.java:46)
        at net.minecraftforge.remapper.RemapperTask$1.run(RemapperTask.java:39)
        at java.lang.Thread.run(Unknown Source)
```
